export const voices = [
    "en-US, AIGenerate1Neural",
    "en-US, AIGenerate2Neural",
    "en-US, AmberNeural",
    "en-US, AnaNeural",
    "en-US, AriaNeural",
    "en-US, AshleyNeural",
    "en-US, BrandonNeural",
    "en-US, ChristopherNeural",
    "en-US, CoraNeural",
    "en-US, DavisNeural",
    "en-US, ElizabethNeural",
    "en-US, EricNeural",
    "en-US, GuyNeural",
    "en-US, JacobNeural",
    "en-US, JaneNeural",
    "en-US, JasonNeural",
    "en-US, JennyMultilingualNeural",
    "en-US, JennyNeural",
    "en-US, MichelleNeural",
    "en-US, MonicaNeural",
    "en-US, NancyNeural",
    "en-US, RogerNeural",
    "en-US, SaraNeural",
    "en-US, SteffanNeural",
    "en-US, TonyNeural",
]
